import Header from "@/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import Container from "@/ui/Container";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "RoadMaps",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div>
          <Container>{children}</Container>
        </div>
        <Footer />
      </body>
    </html>
  );
}
