import "./globals.css";
import { Inter } from "next/font/google";
import MDXProviderWrapper from "./../components/blogs/MDXProviderWrapper";
import Header from "../components/Header";
import Footer from "../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Free Learning Path",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <MDXProviderWrapper>
          <div>{children}</div>
        </MDXProviderWrapper>
        <Footer />
      </body>
    </html>
  );
}
